# Generated by Django 5.2.3 on 2025-06-22 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(help_text='Original resume file uploaded by user', upload_to='uploaded_resumes/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', help_text='Current processing status', max_length=20)),
                ('analysis_results', models.JSONField(blank=True, help_text='AI analysis results stored as JSON', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Uploaded Resume',
                'verbose_name_plural': 'Uploaded Resumes',
                'ordering': ['-created_at'],
            },
        ),
    ]
